#!/bin/bash
# Up to this version is supported.
THISHW="1"
THISFW="3"
# if you want to go back to previous version
THISVERFW="3" 
ANSWERFW=0
ANSWERHW=0

sudo /opt/avnet-iot/iotservices/checkpishrink
# check for pishrink running and exit if so.
if [[ $? == 0 ]]; then
    echo "Starting Smartedge-iiot-gateway ATTINY UPDATE service" 
else
    echo -e "\e[31mPiShrink Running delaying ATTINY UPDATE service"
    exit 1
fi
ANSWERHW=$(dmesg | grep -o 'ATTINY HW REV [0-9]*' | grep -o '[0-9]*'| tr -d '\n' | tail -c 1)
ANSWERFW=$(dmesg | grep -o 'ATTINY FW REV [0-9]*' | grep -o '[0-9]*' | tr -d '\n' | tail -c 1)
echo $ANSWERFW
echo $ANSWERHW

reprogramdate=$(date)
echo $reprogramdate
sudo rm /var/log/attiny_updates.log
sudo touch /var/log/attiny_updates.log
sudo chmod 666 /var/log/attiny_updates.log


Attiny_update_firmware() {
    echo 'Reprogramming ATTiny upgrading to HW REV'  $ANSWERHW  ' to FW REV ' $ANSWERFW ' On ' $reprogramdate  >>/var/log/attiny_updates.log
    sudo systemctl stop ledservice
    sudo systemctl stop buttonservice
    sudo rmmod attiny_led
    sudo rmmod attiny_btn
    sudo rmmod attiny_wdt
    sudo rmmod attiny_mfd
    cd /opt/avnet-iot/utilities/attiny/ver1.$THISVERFW
    sudo ./attiny_pgm_avnet.sh avnet_iot_smc.zip >>/var/log/attiny_updates.log 2>&1
    sudo modprobe attiny_mfd
    sudo modprobe attiny_btn
    sudo modprobe attiny_led
    sudo modprobe attiny_wdt
    while [ -f "/dev/watchdog1" ];
    do
	sleep 2
	echo "waiting for watchdog1"
    done
    
    # Stop it as modprobe will re-enable it.
    echo V | sudo tee /dev/watchdog1
    sudo systemctl enable buttonservice
    sudo systemctl enable ledservice
    sudo systemctl start buttonservice
    sudo systemctl start ledservice
}

#
# Main code.
#
if [[ $ANSWERHW -eq $THISHW ]]; then    
    if [[ $ANSWERFW -lt $THISFW ]]; then
	echo 'ATTiny updating from Version ' $ANSWERHW '.' $ANSWERFW ' To ' $THISHW '.' $THISFW ' On ' $reprogramdate >>/var/log/attiny_updates.log
	Attiny_update_firmware
	echo 'ATTiny up to date HW ' $THISHW ' FW ' $THISFW ' On ' $reprogramdate >>/var/log/attiny_updates.log
    else
	echo 'ATTiny up to date' >>/var/log/attiny_updates.log
    fi
    if [[ $ANSWERFW -eq $THISFW ]]; then
	if [[ $ANSWERFW -ne $THISVERFW ]]; then
	    
	    echo 'ATTiny downgrading from HW ' $ANSWERHW ' FW ' $ANSWERFW ' On ' $reprogramdate >>/var/log/attiny_updates.log
	    Attiny_update_firmware
	    echo 'ATTiny up to date HW ' $THISHW ' FW ' $THISVERFW ' On ' $reprogramdate >>/var/log/attiny_updates.log
   
	fi
	echo 'ATTiny not downgrading'
    fi
    
else
    echo 'ATTiny updating from HW ' $ANSWERHW ' FW ' $ANSWERFW ' On ' $reprogramdate 'Unsupported'  >>/var/log/attiny_updates.log
fi
    
    
