#!/bin/bash
cd /opt/avnet-iot/iotservices
sudo /opt/avnet-iot/iotservices/checkpishrink
# check for pishrink running and exit if so.
if [[ $? == 0 ]]; then
    echo "Starting Smartedge-iiot-gateway Button service" 
else
    echo -e "\e[31mPiShrink Running delaying Button service"
    exit 1
fi
/usr/bin/sudo /opt/avnet-iot/iotservices/stopwd
sleep 1 
while true; do
    /usr/bin/sudo -E python -u /opt/avnet-iot/iotservices/button.py >/dev/null 2>&1 
    sleep 60
    echo "Button python restart" >>/var/log/button.log
done & 
