#!/bin/bash
cd /opt/avnet-iot/iotservices
sudo rm /sbin/reboot
sudo ln -s /opt/avnet-iot/iotservices/reboot /sbin/reboot
sudo cp hostapd.conf /etc/hostapd/hostapd.conf
sudo cat /proc/cpuinfo | grep Serial | cut -d ':' -f2 | cut -b 10-17 | tr -d "\r\n" | tr -d " " >>/etc/hostapd/hostapd.conf
sleep 2

sudo cp /etc/default/hostapd.ap /etc/default/hostapd
sudo cp /etc/dhcpcd.conf.ap /etc/dhcpcd.conf
sudo cp /etc/dnsmasq.conf.ap /etc/dnsmasq.conf
sudo systemctl daemon-reload
sudo systemctl enable dhcpcd.service
sudo systemctl enable hostapd.service
sudo systemctl enable dnsmasq.service
sudo systemctl start hostapd.service
sudo systemctl start dnsmasq.service
sudo systemctl start dhcpcd.service


