#!/bin/bash
cd /opt/avnet-iot/iotservices
sudo /opt/avnet-iot/iotservices/checkpishrink
# check for pishrink running and exit if so.
if [[ $? == 0 ]]; then
    echo "Starting Smartedge-iiot-gateway ConfigurationMode LED service" 
else
    echo -e "\e[31mPiShrink Running delaying LED service"
    exit 1
fi
sudo /opt/avnet-iot/iotservices/stopwd
sudo -E python -u /opt/avnet-iot/iotservices/led.py >/dev/null 2>&1
echo "Led python restart" >>/var/log/led.log
