#!/bin/bash
sudo /opt/avnet-iot/iotservices/checkpishrink
# check for pishrink running and exit if so.
if [[ $? == 0 ]]; then
    echo "Starting Smartedge-iiot-gateway SDK " 
else
    echo -e "\e[31mPiShrink Running delaying SDK service"
    exit 1
fi
cd /opt/avnet-iot/IoTConnect/sample
if ping -q -c 1 -W 1 8.8.8.8 >/dev/null; then
    /usr/bin/sudo -E python -u /opt/avnet-iot/IoTConnect/sample/example.py 
else
    echo "No network, restarting in 60 seconds" | sudo tee >>/var/log/iot.log
fi
